apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-dns
  includeCRDs: true
  releaseName: external-dns
  namespace: external-dns
  version: 1.16.1
  repo: https://kubernetes-sigs.github.io/external-dns/
  valuesInline:
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token-secret
          key: cloudflare-api-token-secret
    extraArgs:
    - --zone-id-filter=3b3010f2e7d9a53b4bc7b698d28e9076
    policy: sync
    provider:
      name: cloudflare
    txtOwnerId: "rpi-external-dns"

resources:
- sa-crb.yaml
- secrets.yaml
- secretstore.yaml
