apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: external-dns-vault
    kind: SecretStore
  target:
    name: cloudflare-api-token-secret
  data:
  - secretKey: cloudflare-api-token-secret
    remoteRef:
      key: secret/cloudflare/api-keys/external-dns
      property: api-token
